# 📊 Stack Overflow Survey Analysis

Improved version (clean, structured, portfolio-ready)

## 🔧 Imports and Data Loading

In [25]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Colab Notebooks/survey_results_public.csv'

pathSchema = '/content/drive/MyDrive/Colab Notebooks/survey_results_schema.csv'

df = pd.read_csv(path, encoding = 'utf-8')

schema = pd.read_csv(pathSchema, encoding = 'utf-8')


df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/tmp/ipykernel_4818/2213491263.py:10: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, encoding = 'utf-8')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

## ✅ Task 1 — Total Respondents

In [26]:
n = df['ResponseId'].nunique()
print(f"Total respondents: {n:,}")

Total respondents: 49,191

## ✅ Task 2 — Respondents with Full Answers

In [27]:
questions = set(schema['qname'])
columns = set(df.columns)

common_questions = list(questions.intersection(columns))
df_filtered = df[common_questions]

df_clean = df_filtered[df_filtered.notna().all(axis=1)]

print(f"Questions used: {len(common_questions)}")
print(f"Respondents with full answers: {len(df_clean):,}")

Questions used: 126
Respondents with full answers: 0

## ✅ Task 3 — Work Experience Statistics

In [28]:
stats = pd.Series({
    'Mean': round(df['WorkExp'].mean(),2),
    'Median': df['WorkExp'].median(),
    'Mode': df['WorkExp'].mode()[0]
})

print(stats)

Mean      13.37
Median    10.00
Mode      10.00
dtype: float64

## ✅ Task 4 — Remote Workers

In [29]:
remote_count = df[df['RemoteWork'] == 'Remote'].shape[0]
print(f"Remote workers: {remote_count:,}")

Remote workers: 10,931

## ✅ Task 5 — Python Popularity

In [30]:
python_users = df['LanguageHaveWorkedWith'].str.contains('Python', case = False, na=False)
percentage = python_users.mean() * 100

print(f"Python users: {percentage:.2f}%")

Python users: 37.54%

## ✅ Task 6 — Online Learning

In [31]:
online_learners = df['LearnCode'].str.contains('Online', case=False, na=False)
count_online = online_learners.sum()

print(f"Online learners: {count_online:,}")

Online learners: 28,352

## ✅ Task 7 — Python Developers Compensation by Country

In [32]:
df['is_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', case = False, na=False)

python_df = df[df['is_python']]

comp = python_df.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).dropna()
comp = comp.sort_values(by='mean', ascending=False)

comp.head()

                                   mean    median
Country
Oman                      390135.000000  390135.0
Andorra                   226103.500000  226103.5
Viet Nam                  218837.166667    8254.0
United States of America  173298.590211  150000.0
Switzerland               156456.600000  142592.0

## ✅ Task 8 — Top 5 Highest Paid Education Levels

In [33]:
top5 = df.dropna(subset=['ConvertedCompYearly']) \
    .sort_values(by='ConvertedCompYearly', ascending=False) \
    .head(5).reset_index()

top5[['EdLevel', 'ConvertedCompYearly']]

                                           EdLevel  ConvertedCompYearly
0              Associate degree (A.A., A.S., etc.)           50000000.0
1  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           33552715.0
2              Associate degree (A.A., A.S., etc.)           18387548.0
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           15430267.0
4  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           13921760.0

## ⭐ Task 9 — Python by Age

In [34]:
df['is_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', case = False, na=False)

age_python = df.groupby('Age')['is_python'].mean() * 100
age_python.sort_values(ascending=False)

Age
18-24 years old      40.000000
45-54 years old      38.629482
55-64 years old      37.242955
25-34 years old      36.939282
35-44 years old      36.719281
65 years or older    31.634820
Prefer not to say    31.216931
Name: is_python, dtype: float64

## ⭐ Task 10 — Top Industries (High-paid Remote)

In [35]:
threshold = df['ConvertedCompYearly'].quantile(0.75)

filtered = df[
    (df['ConvertedCompYearly'] > threshold) &
    (df['RemoteWork'] == 'Remote')
]

industries = filtered['Industry'].value_counts()
industries.head()

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Name: count, dtype: int64